Repository ITU-BDSA23-GROUP17/Chirp, pull requests merged in 2023-12, with the labels that each got.

#151 Like button works now but the UI does not update
  src/Chirp.Core/CheepInfoDTO.cs
  src/Chirp.Core/IReactionRepository.cs
  src/Chirp.Core/IReactionTypeRepository.cs
  src/Chirp.Infrastructure/DbInitializer.cs
  src/Chirp.Infrastructure/Migrations/20231130114328_newMigration.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231130114328_newMigration.cs
  src/Chirp.Infrastructure/Reaction.cs
  src/Chirp.Infrastructure/ReactionRepository.cs
  src/Chirp.Infrastructure/ReactionTypeRepository.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_TimeLinePartial.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
Labels: enhancement

#162 Like counter works now
  src/Chirp.Core/CheepInfoDTO.cs
  src/Chirp.Core/IReactionRepository.cs
  src/Chirp.Infrastructure/Migrations/20231206091814_newMigration.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231206091814_newMigration.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Infrastructure/ReactionRepository.cs
  src/Chirp.Web/Pages/Hashtag.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_TimeLinePartial.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  test/Chirp.Web.Test/Integration.Test/Integration.Test.csproj
  test/Chirp.Web.Test/Playwright.Test/PlaywrightTests/PlaywrightTests.csproj
Labels: enhancement

#173 Fix/removing reaction type
  src/Chirp.Core/IReactionRepository.cs
  src/Chirp.Core/IReactionTypeRepository.cs
  src/Chirp.Core/ReactionDTO.cs
  src/Chirp.Core/ReactionTypeDTO.cs
  src/Chirp.Infrastructure/ChirpDBContext.cs
  src/Chirp.Infrastructure/DbInitializer.cs
  src/Chirp.Infrastructure/Migrations/20231218112022_newMigration.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231218112022_newMigration.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Infrastructure/Reaction.cs
  src/Chirp.Infrastructure/ReactionRepository.cs
  src/Chirp.Infrastructure/ReactionType.cs
  src/Chirp.Infrastructure/ReactionTypeRepository.cs
  src/Chirp.Web/Pages/Hashtag.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_TimeLinePartial.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: refactor

#182 add unit tests
  src/Chirp.Core/IAuthorRepository.cs
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Infrastructure/AuthorRepository.cs
  src/Chirp.Infrastructure/CheepRepository.cs
  src/Chirp.Web/Pages/BaseModel.cshtml.cs
  src/Chirp.Web/Pages/Cheep.cshtml.cs
  src/Chirp.Web/Pages/Hashtag.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
  src/Chirp.Web/Pages/Shared/_ProfilePartial.cshtml
  src/Chirp.Web/Pages/Shared/_TimeLinePartial.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  test/Chirp.Infrastructure.Test/HashtagTextRepository.cs
  test/Chirp.Infrastructure.Test/InfrastructureUnitTests.cs
  test/Chirp.Web.Test/Integration.Test/IntegrationTest.cs
Labels: test

#185 Report.md added + GitHub action Workflow with pandocs
  .github/workflows/pandocs.yml
  .vscode/settings.json
  2023_itubdsa_group_17_report.pdf
  docs/images/ITU_logo.jpg
  docs/images/plantuml/AuthorDTO.puml
  docs/images/plantuml/AuthorInfoDTO.puml
  docs/images/plantuml/CheepDTO.puml
  docs/images/plantuml/CheepInfoDTO.puml
  docs/images/plantuml/FollowDTO.puml
  docs/images/plantuml/HashtagDTO.puml
  docs/images/plantuml/HashtagTextDTO.puml
  docs/images/plantuml/IAuthorRepository.puml
  docs/images/plantuml/ICheepRepository.puml
  docs/images/plantuml/IFollowRepository.puml
  docs/images/plantuml/IHashtagRepository.puml
  docs/images/plantuml/IHashtagTextRepository.puml
  docs/images/plantuml/IReactionRepository.puml
  docs/images/plantuml/ReactionDTO.puml
  docs/images/plantuml/include.puml
  docs/images/uml/Domain-model-Chirp.Core.drawio.png
  docs/report.md
  docs/template/custom-template.tex
Labels: enhancement
